/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.pagos;

import controller.Control;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.time.LocalDate;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Pago;

/**
 *
 * @author Daniel
 */
public class ListadoPagos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListadoTrabajadores
     */
    public ListadoPagos() {
        initComponents();
        yearInp.setMaximum(LocalDate.now().getYear());

        monthInp.setYearChooser(yearInp);

        yearInp.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if (yearInp.getYear() > LocalDate.now().getYear()) {
                    listar.setEnabled(false);
                } else {
                    listar.setEnabled(true);
                }
            }
        });

        monthInp.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if (yearInp.getYear() == LocalDate.now().getYear() && monthInp.getMonth() > LocalDate.now().getMonthValue() - 1) {
                    listar.setEnabled(false);
                } else {
                    listar.setEnabled(true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        listar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        monthInp = new com.toedter.calendar.JMonthChooser();
        yearInp = new com.toedter.calendar.JYearChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listado de pagos");
        setMinimumSize(new java.awt.Dimension(550, 400));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trabajador", "Días trabajados", "Evaluación", "Salario base", "Salario adicional", "Monto total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        listar.setText("Listar");
        listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione el mes a listar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(monthInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(yearInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listar)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(monthInp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yearInp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed
        List<Pago> pagos = Control.pagosJPA.findByMonthAndYear(monthInp.getMonth() + 1, yearInp.getYear());
        DefaultTableModel model = ((DefaultTableModel) jTable1.getModel());
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        for (int i = 0; i < pagos.size(); i++) {
            model.addRow(new Object[]{});
            
            Pago p = pagos.get(i);
            double salarioBase = p.getIdTrabajador().getIdEscala().getSalario();
            Double salarioAdic = p.getPagoAdicional();

            jTable1.setValueAt(p.getIdTrabajador(), i, 0);
            jTable1.setValueAt(p.getDiasTrabajados(), i, 1);
            jTable1.setValueAt(p.getEvaluacion(), i, 2);
            jTable1.setValueAt(salarioBase, i, 3);
            jTable1.setValueAt(salarioAdic != null ? salarioAdic : 0d, i, 4);
            jTable1.setValueAt(salarioBase + (salarioAdic != null ? salarioAdic : 0d), i, 5);
        }

    }//GEN-LAST:event_listarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton listar;
    private com.toedter.calendar.JMonthChooser monthInp;
    private com.toedter.calendar.JYearChooser yearInp;
    // End of variables declaration//GEN-END:variables
}
