/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.trabajadores;

import Utils.Utils;
import controller.Control;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Clasificacion;
import model.GrupoEscala;
import model.Trabajador;

/**
 *
 * @author Daniel
 */
public class AddTrabajador extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddTrabajador
     */
    public AddTrabajador() {
        initComponents();

        Clasificacion[] c = {};
        classif.setModel(new DefaultComboBoxModel<>(Control.clasiffJPA.findClasificacionEntities().toArray(c)));

        GrupoEscala[] g = {};
        ge.setModel(new DefaultComboBoxModel<>(Control.grupoEscalaJPA.findGrupoEscalaEntities().toArray(g)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ape1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ape2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ci = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        classif = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ge = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Nuevo trabajador");
        setMinimumSize(new java.awt.Dimension(450, 500));
        setPreferredSize(new java.awt.Dimension(450, 500));

        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 20, 30));

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1);
        jPanel1.add(nombre1);

        jLabel2.setText("Segundo nombre");
        jPanel1.add(jLabel2);
        jPanel1.add(nombre2);

        jLabel3.setText("Primer Apellido");
        jPanel1.add(jLabel3);
        jPanel1.add(ape1);

        jLabel4.setText("Segundo Apellido");
        jPanel1.add(jLabel4);
        jPanel1.add(ape2);

        jLabel5.setText("Carné de identidad");
        jPanel1.add(jLabel5);
        jPanel1.add(ci);

        jLabel6.setText("Clasificación");
        jPanel1.add(jLabel6);

        jPanel1.add(classif);

        jLabel7.setText("Grupo - escala");
        jPanel1.add(jLabel7);

        jPanel1.add(ge);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jButton1.setText("Guardar");
        jButton1.setMinimumSize(new java.awt.Dimension(73, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(73, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Utils.validateEmptyTF(nombre1)
                && Utils.validateEmptyTF(ape1)
                && Utils.validateEmptyTF(ape2)
                && Utils.validateEmptyTF(ci)
                && Utils.validateNumbersTF(ci)
                && Utils.validateLengthTF(ci, 11)) {
            Trabajador t = new Trabajador();

            t.setNombre(nombre1.getText());
            t.setNombre2(nombre2.getText());
            t.setApellido1(ape1.getText());
            t.setApellido2(ape2.getText());
            t.setCi(ci.getText());
            t.setIdClasificacion((Clasificacion) classif.getSelectedItem());
            t.setIdEscala((GrupoEscala) ge.getSelectedItem());

            Control.trabajJPA.create(t);

            JOptionPane.showMessageDialog(this, "Trabajador creado", "Info", JOptionPane.INFORMATION_MESSAGE);

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Existen campos con valores incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ape1;
    private javax.swing.JTextField ape2;
    private javax.swing.JTextField ci;
    private javax.swing.JComboBox<Clasificacion> classif;
    private javax.swing.JComboBox<GrupoEscala> ge;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField nombre2;
    // End of variables declaration//GEN-END:variables
}
