/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.trabajadores;

import Utils.Utils;
import controller.Control;
import controller.exceptions.IllegalOrphanException;
import controller.exceptions.NonexistentEntityException;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Pago;
import model.Trabajador;
import model.Utilidades;

/**
 *
 * @author Daniel
 */
public class DelTrabajador extends javax.swing.JInternalFrame {

    private Trabajador t;

    /**
     * Creates new form DelTrabajador
     */
    public DelTrabajador() {
        initComponents();

        Trabajador[] trabs = {};
        trabs = Control.trabajJPA.findTrabajadorEntities().toArray(trabs);
        trabajadorBox.setModel(new DefaultComboBoxModel<>(trabs));

        trabajadorBox.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                Trabajador o = (Trabajador) e.getItem();
                jButton1.setEnabled(o != null);
                t = o;
            }
        });

        t = trabs[0];
        jButton1.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        trabajadorBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setTitle("Eliminar trabajador");
        setMaximumSize(new java.awt.Dimension(450, 150));
        setMinimumSize(new java.awt.Dimension(450, 150));
        setPreferredSize(new java.awt.Dimension(450, 150));

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel8.setText("Seleccione el trabajador");
        jPanel5.add(jLabel8);

        trabajadorBox.setMinimumSize(new java.awt.Dimension(250, 25));
        trabajadorBox.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel5.add(trabajadorBox);

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jButton1.setText("Eliminar");
        jButton1.setEnabled(false);
        jButton1.setMinimumSize(new java.awt.Dimension(73, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(73, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar el trabajador " + Utils.fullName(t) + "?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        ) == JOptionPane.YES_OPTION) {
            try {
                delete();
                Control.trabajJPA.destroy(t.getId());
                JOptionPane.showMessageDialog(this, "Trabajador eliminado", "Info", JOptionPane.INFORMATION_MESSAGE);
            } catch (IllegalOrphanException | NonexistentEntityException ex) {
                JOptionPane.showMessageDialog(this, "Otra excep " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void delete() throws NonexistentEntityException {
        List<Utilidades> uts = t.getUtilidadesList();

        for (int i = 0; i < uts.size(); i++) {
            Control.utilidJPA.destroy(uts.get(i).getId());
        }

        List<Pago> pags = t.getPagoList();

        for (int i = 0; i < pags.size(); i++) {
            Control.pagosJPA.destroy(pags.get(i).getId());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<Trabajador> trabajadorBox;
    // End of variables declaration//GEN-END:variables
}
