/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.trabajadores;

import Utils.Utils;
import controller.Control;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Trabajador;

/**
 *
 * @author Daniel
 */
public class ListadoTrabajadores extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListadoTrabajadores
     */
    public ListadoTrabajadores() {
        initComponents();

        List<Trabajador> trabaj = Control.trabajJPA.findTrabajadorEntities();

        for (int i = 0; i < trabaj.size(); i++) {
            ((DefaultTableModel) jTable1.getModel()).addRow(new Object[]{});
            Trabajador t = trabaj.get(i);
            jTable1.setValueAt(Utils.fullName(t), i, 0);
            jTable1.setValueAt(t.getCi(), i, 1);
            jTable1.setValueAt(t.getIdClasificacion().getDescripcion(), i, 2);
            jTable1.setValueAt(t.getIdEscala().getDescripcion(), i, 3);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listado de trabajadores");
        setMinimumSize(new java.awt.Dimension(550, 400));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre completo", "Carné de identidad", "Clasificación", "Grupo Escala"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
