/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.trabajadores;

import Utils.Utils;
import controller.Control;
import controller.exceptions.NonexistentEntityException;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Clasificacion;
import model.GrupoEscala;
import model.Trabajador;

/**
 *
 * @author Daniel
 */
public class ModTrabajador extends javax.swing.JInternalFrame {

    Trabajador t = null;

    /**
     * Creates new form AddTrabajador
     */
    public ModTrabajador() {
        initComponents();

        Trabajador[] trabs = {};
        trabs = Control.trabajJPA.findTrabajadorEntities().toArray(trabs);
        trabajadorBox.setModel(new DefaultComboBoxModel<>(trabs));

        Clasificacion[] c = {};
        classif.setModel(new DefaultComboBoxModel<>(Control.clasiffJPA.findClasificacionEntities().toArray(c)));

        GrupoEscala[] g = {};
        ge.setModel(new DefaultComboBoxModel<>(Control.grupoEscalaJPA.findGrupoEscalaEntities().toArray(g)));

        trabajadorBox.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                Trabajador o = (Trabajador) e.getItem();

                if (o != null) {
                    t = o;
                    activeFields(true);
                    fillData(o);

                } else {
                    t = null;
                    activeFields(false);
                    fillData(null);
                }
            }
        });

        trabajadorBox.setSelectedIndex(0);
        t = trabs[0];
        fillData(t);
        activeFields(true);
    }

    private void fillData(Trabajador o) {
        if (o != null) {
            nombre1.setText(o.getNombre());
            nombre2.setText(o.getNombre2());
            ape1.setText(o.getApellido1());
            ape2.setText(o.getApellido2());
            ci.setText(o.getCi());
            classif.setSelectedItem(o.getIdClasificacion());
            ge.setSelectedItem(o.getIdEscala());
        } else {
            nombre1.setText("");
            nombre2.setText("");
            ape1.setText("");
            ape2.setText("");
            ci.setText("");
            classif.setSelectedItem(null);
            ge.setSelectedItem(null);
        }
    }

    private void activeFields(boolean active) {
        if (active) {
            nombre1.setEnabled(true);
            nombre2.setEnabled(true);
            ape1.setEnabled(true);
            ape2.setEnabled(true);
            ci.setEnabled(true);
            classif.setEnabled(true);
            ge.setEnabled(true);

            jButton1.setEnabled(true);
        } else {
            nombre1.setEnabled(false);
            nombre2.setEnabled(false);
            ape1.setEnabled(false);
            ape2.setEnabled(false);
            ci.setEnabled(false);
            classif.setEnabled(false);
            ge.setEnabled(false);

            jButton1.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ape1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ape2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ci = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        classif = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ge = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        trabajadorBox = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Modificar trabajador");
        setMinimumSize(new java.awt.Dimension(450, 500));
        setPreferredSize(new java.awt.Dimension(450, 500));

        data.setEnabled(false);
        data.setLayout(new java.awt.GridLayout(7, 2, 20, 30));

        jLabel1.setText("Nombre");
        data.add(jLabel1);

        nombre1.setEnabled(false);
        data.add(nombre1);

        jLabel2.setText("Segundo nombre");
        data.add(jLabel2);

        nombre2.setEnabled(false);
        data.add(nombre2);

        jLabel3.setText("Primer Apellido");
        data.add(jLabel3);

        ape1.setEnabled(false);
        data.add(ape1);

        jLabel4.setText("Segundo Apellido");
        data.add(jLabel4);

        ape2.setEnabled(false);
        data.add(ape2);

        jLabel5.setText("Carné de identidad");
        data.add(jLabel5);

        ci.setEnabled(false);
        data.add(ci);

        jLabel6.setText("Clasificación");
        data.add(jLabel6);

        classif.setEnabled(false);
        data.add(classif);

        jLabel7.setText("Grupo - escala");
        data.add(jLabel7);

        ge.setEnabled(false);
        data.add(ge);

        getContentPane().add(data, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jButton1.setText("Guardar");
        jButton1.setMinimumSize(new java.awt.Dimension(73, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(73, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel8.setText("Seleccione el trabajador");
        jPanel5.add(jLabel8);

        trabajadorBox.setMinimumSize(new java.awt.Dimension(250, 25));
        trabajadorBox.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel5.add(trabajadorBox);

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Utils.validateEmptyTF(nombre1)
                && Utils.validateEmptyTF(ape1)
                && Utils.validateEmptyTF(ape2)
                && Utils.validateEmptyTF(ci)
                && Utils.validateNumbersTF(ci)
                && Utils.validateLengthTF(ci, 11)) {

            t.setNombre(nombre1.getText());
            t.setNombre2(nombre2.getText());
            t.setApellido1(ape1.getText());
            t.setApellido2(ape2.getText());
            t.setCi(ci.getText());
            t.setIdClasificacion((Clasificacion) classif.getSelectedItem());
            t.setIdEscala((GrupoEscala) ge.getSelectedItem());

            try {
                Control.trabajJPA.edit(t);
            } catch (NonexistentEntityException ex) {
                JOptionPane.showMessageDialog(this, "No existe la entidad", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Otra excep " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

            JOptionPane.showMessageDialog(this, "Trabajador modificado", "Info", JOptionPane.INFORMATION_MESSAGE);

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Existen campos con valores incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ape1;
    private javax.swing.JTextField ape2;
    private javax.swing.JTextField ci;
    private javax.swing.JComboBox<Clasificacion> classif;
    private javax.swing.JPanel data;
    private javax.swing.JComboBox<GrupoEscala> ge;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField nombre2;
    private javax.swing.JComboBox<Trabajador> trabajadorBox;
    // End of variables declaration//GEN-END:variables
}
